import poolCircuit from "@/circuits/shielded_pool.json";
import complianceCircuit from "@/circuits/compliance.json";
import disclosureCircuit from "@/circuits/disclosure.json";
import { runProof, type ProofResult, type ProofStage } from "./prover-core";
import type { ProverWorkerRequest, ProverWorkerResponse } from "./prover.worker";

// The recurring circuit JSON is generated by `nargo compile` in
// circuits/recurring and copied to this directory.  Import it lazily so a
// missing file only causes failures in the recurring flow rather than
// breaking the whole bundle at startup.
let recurringCircuit: Record<string, unknown> | null = null;
async function getRecurringCircuit(): Promise<Record<string, unknown>> {
  if (!recurringCircuit) {
    try {
      // Dynamic import so the bundle doesn't hard-fail when the JSON hasn't
      // been compiled yet (e.g. CI that only runs contract/frontend tests).
      recurringCircuit = (await import("@/circuits/recurring.json")) as Record<string, unknown>;
    } catch {
      throw new Error(
        "Recurring circuit not compiled — run `nargo compile` in circuits/recurring and copy the output to frontend/src/circuits/recurring.json",
      );
    }
  }
  return recurringCircuit;
}

export type { ProofResult, ProofStage };

let worker: Worker | null = null;
let nextRequestId = 0;

function getWorker(): Worker | null {
  if (typeof Worker === "undefined") return null;
  if (!worker) {
    worker = new Worker(new URL("./prover.worker.ts", import.meta.url), {
      type: "module",
    });
  }
  return worker;
}

/**
 * Runs proof generation in a Web Worker so the main thread (and the UI's
 * spinner/animations) stays responsive. Falls back to running inline when
 * Workers aren't available (SSR, unit tests).
 */
async function generateProof(
  circuit: Record<string, unknown>,
  inputs: Record<string, string | string[]>,
  onProgress?: (stage: ProofStage) => void,
): Promise<ProofResult> {
  const w = getWorker();
  if (!w) {
    return runProof(circuit, inputs, onProgress);
  }

  const id = ++nextRequestId;

  return new Promise<ProofResult>((resolve, reject) => {
    function onMessage(event: MessageEvent<ProverWorkerResponse>) {
      const data = event.data;
      if (data.id !== id) return;

      if (data.type === "progress") {
        onProgress?.(data.stage);
      } else if (data.type === "done") {
        cleanup();
        resolve({ proof: data.proof, publicInputs: data.publicInputs });
      } else if (data.type === "error") {
        cleanup();
        reject(new Error(data.message));
      }
    }

    function onError(event: ErrorEvent) {
      cleanup();
      reject(event.error instanceof Error ? event.error : new Error(event.message));
    }

    function cleanup() {
      w!.removeEventListener("message", onMessage);
      w!.removeEventListener("error", onError);
    }

    w.addEventListener("message", onMessage);
    w.addEventListener("error", onError);

    const request: ProverWorkerRequest = { id, circuit, inputs };
    w.postMessage(request);
  });
}

/**
 * Proves a spend of one note: `withdrawAmount` of its `amount` is paid out and
 * the remainder is re-shielded into a new note under `changeNullifier` /
 * `changeSecret`.
 *
 * A change note is always produced, even for a full withdrawal where the
 * remainder is zero, so that a full and a partial spend are indistinguishable
 * on-chain. The caller must therefore always store the change note — see the
 * withdraw page, which saves it before submitting.
 *
 * Amounts are decimal strings of token base units. They must not be hex: Noir
 * would read a `0x`-prefixed amount as a different number than the contract's
 * big-endian byte decoding does, and the payout would silently disagree with
 * what the note is worth.
 */
export async function proveWithdrawal(
  inputs: {
    nullifier: string;
    secret: string;
    amount: string;
    withdrawAmount: string;
    changeNullifier: string;
    changeSecret: string;
    changeCommitment: string;
    root: string;
    nullifierHash: string;
    recipientHash: string;
    pathSiblings: string[];
    pathBits: number[];
  },
  onProgress?: (stage: ProofStage) => void,
): Promise<ProofResult> {
  return generateProof(
    poolCircuit as Record<string, unknown>,
    {
      nullifier: ensureHex(inputs.nullifier),
      secret: ensureHex(inputs.secret),
      amount: decimal(inputs.amount),
      change_nullifier: ensureHex(inputs.changeNullifier),
      change_secret: ensureHex(inputs.changeSecret),
      root: ensureHex(inputs.root),
      nullifier_hash: ensureHex(inputs.nullifierHash),
      recipient: ensureHex(inputs.recipientHash),
      withdraw_amount: decimal(inputs.withdrawAmount),
      change_commitment: ensureHex(inputs.changeCommitment),
      path_bits: inputs.pathBits.map(String),
      path_siblings: inputs.pathSiblings.map(ensureHex),
    },
    onProgress,
  );
}

export async function proveCompliance(
  inputs: {
    kycPreimage: string;
    nullifier: string;
    secret: string;
    amount: string;
    auditorKey: string;
    merkleRoot: string;
    kycHash: string;
    disclosedAmount: string;
    pathSiblings: string[];
    pathBits: number[];
  },
  onProgress?: (stage: ProofStage) => void,
): Promise<ProofResult> {
  return generateProof(
    complianceCircuit as Record<string, unknown>,
    {
      kyc_preimage: ensureHex(inputs.kycPreimage),
      nullifier: ensureHex(inputs.nullifier),
      secret: ensureHex(inputs.secret),
      amount: decimal(inputs.amount),
      auditor_key: ensureHex(inputs.auditorKey),
      merkle_root: ensureHex(inputs.merkleRoot),
      kyc_hash: ensureHex(inputs.kycHash),
      disclosed_amount: decimal(inputs.disclosedAmount),
      path_bits: inputs.pathBits.map(String),
      path_siblings: inputs.pathSiblings.map(ensureHex),
    },
    onProgress,
  );
}

export async function proveDisclosure(
  inputs: {
    kycPreimage: string;
    nullifier: string;
    secret: string;
    amount: string;
    auditorKey: string;
    merkleRoot: string;
    kycHash: string;
    threshold: string;
    pathSiblings: string[];
    pathBits: number[];
  },
  onProgress?: (stage: ProofStage) => void,
): Promise<ProofResult> {
  return generateProof(
    disclosureCircuit as Record<string, unknown>,
    {
      kyc_preimage: ensureHex(inputs.kycPreimage),
      nullifier: ensureHex(inputs.nullifier),
      secret: ensureHex(inputs.secret),
      amount: decimal(inputs.amount),
      auditor_key: ensureHex(inputs.auditorKey),
      merkle_root: ensureHex(inputs.merkleRoot),
      kyc_hash: ensureHex(inputs.kycHash),
      threshold: decimal(inputs.threshold),
      path_bits: inputs.pathBits.map(String),
      path_siblings: inputs.pathSiblings.map(ensureHex),
    },
    onProgress,
  );
}

function ensureHex(v: string): string {
  if (v.startsWith("0x")) return v;
  return "0x" + v;
}

/** Normalizes an amount to the plain decimal form Noir reads as a number. */
function decimal(v: string): string {
  return BigInt(v).toString(10);
}

/**
 * Proves a recurring-authorization setup: spends one note and produces an
 * `auth_commitment` and `change_commitment` that `authorize_recurring` stores
 * on-chain.
 *
 * The proof runs in a Web Worker (same path as proveWithdrawal) and produces
 * eight public inputs:
 *   root, note_nullifier_hash, auth_commitment, recipient,
 *   max_amount, period_secs, max_uses, change_commitment.
 *
 * `maxAmount` and `maxUses` are decimal token-base-unit / count strings.
 * `periodSecs` is a number of seconds as a decimal string.
 *
 * The caller must save the auth record *before* submitting the transaction.
 */
export async function proveRecurringAuthorization(
  inputs: {
    // Note opening
    nullifier: string;
    secret: string;
    amount: string;
    // Authorization parameters
    authNullifier: string;
    recipient: string; // recipient hash (same as withdrawal recipient hash)
    maxAmount: string;
    periodSecs: string;
    maxUses: string;
    // Change note
    changeNullifier: string;
    changeSecret: string;
    changeCommitment: string;
    // Merkle proof
    root: string;
    nullifierHash: string;
    pathSiblings: string[];
    pathBits: number[];
  },
  onProgress?: (stage: ProofStage) => void,
): Promise<ProofResult> {
  const circuit = await getRecurringCircuit();
  return generateProof(
    circuit,
    {
      nullifier: ensureHex(inputs.nullifier),
      secret: ensureHex(inputs.secret),
      amount: decimal(inputs.amount),
      auth_nullifier: ensureHex(inputs.authNullifier),
      recipient: ensureHex(inputs.recipient),
      max_amount: decimal(inputs.maxAmount),
      period_secs: decimal(inputs.periodSecs),
      max_uses: decimal(inputs.maxUses),
      change_nullifier: ensureHex(inputs.changeNullifier),
      change_secret: ensureHex(inputs.changeSecret),
      root: ensureHex(inputs.root),
      note_nullifier_hash: ensureHex(inputs.nullifierHash),
      change_commitment: ensureHex(inputs.changeCommitment),
      path_bits: inputs.pathBits.map(String),
      path_siblings: inputs.pathSiblings.map(ensureHex),
    },
    onProgress,
  );
}
